export class InformationchampionshipModel {
	id: number;
	name: string;
	league: number;
	championship: number;
	
}
export const INFORMATIONCHAMPIONSHIPS: InformationchampionshipModel[] = [
  	{id: 1, name: 'Squadre', league: 1, championship: 1},
  	{id: 2, name: 'Classifica', league: 1, championship: 1},
  	{id: 3, name: 'Calendario', league: 1, championship: 1},
	{id: 4, name: 'Squadre', league: 2, championship: 2},
	{id: 5, name: 'Classifica', league: 2, championship: 2},
  	{id: 6, name: 'Calendario', league: 2, championship: 2},
	{id: 7, name: 'Squadre', league: 3, championship: 3},
	{id: 8, name: 'Classifica', league: 3, championship: 3},
  	{id: 9, name: 'Calendario', league: 3, championship: 3},
	{id: 10, name: 'Squadre', league: 4, championship: 4},
	{id: 11, name: 'Classifica', league: 4, championship: 4},  
  	{id: 12, name: 'Calendario', league: 4, championship: 4},
	{id: 13, name: 'Squadre', league: 5, championship: 5},
	{id: 14, name: 'Classifica', league: 5, championship: 5},
  	{id: 15, name: 'Calendario', league: 5, championship: 5},
	{id: 16, name: 'Squadre', league: 6, championship: 6},
	{id: 17, name: 'Classifica', league: 6, championship: 6},
	{id: 18, name: 'Calendario', league: 6, championship: 6},
	{id: 19, name: 'Squadre', league: 7, championship: 7},
	{id: 20, name: 'Classifica', league: 7, championship: 7},
	{id: 21, name: 'Calendario', league: 7, championship: 7},
	{id: 22, name: 'Squadre', league: 8, championship: 8},
	{id: 23, name: 'Classifica', league: 8, championship: 8},
	{id: 24, name: 'Calendario', league: 8, championship: 8},
	{id: 25, name: 'Squadre', league: 9, championship: 9},
	{id: 26, name: 'Classifica', league: 9, championship: 9},
	{id: 27, name: 'Calendario', league: 9, championship: 9},
	{id: 28, name: 'Squadre', league: 10, championship: 10},
	{id: 29, name: 'Classifica', league: 10, championship: 10},
	{id: 30, name: 'Calendario', league: 10, championship: 10},
	{id: 31, name: 'Squadre', league: 11, championship: 11},
	{id: 32, name: 'Classifica', league: 11, championship: 11},
	{id: 33, name: 'Calendario', league: 11, championship: 11},
	{id: 34, name: 'Squadre', league: 12, championship: 12},
	{id: 35, name: 'Classifica', league: 12, championship: 12},
	{id: 36, name: 'Calendario', league: 12, championship: 12},
	{id: 37, name: 'Squadre', league: 13, championship: 13},
	{id: 38, name: 'Classifica', league: 13, championship: 13},
	{id: 39, name: 'Calendario', league: 13, championship: 13},
	{id: 40, name: 'Squadre', league: 14, championship: 14},
	{id: 41, name: 'Classifica', league: 14, championship: 14},
	{id: 42, name: 'Calendario', league: 14, championship: 14},
	{id: 43, name: 'Squadre', league: 15, championship: 15},
	{id: 44, name: 'Classifica', league: 15, championship: 15},
	{id: 45, name: 'Calendario', league: 15, championship: 15},
	{id: 46, name: 'Squadre', league: 16, championship: 16},
	{id: 47, name: 'Classifica', league: 16, championship: 16},
	{id: 48, name: 'Calendario', league: 16, championship: 16},
	{id: 49, name: 'Squadre', league: 17, championship: 17},
	{id: 50, name: 'Classifica', league: 17, championship: 17},
	{id: 51, name: 'Calendario', league: 17, championship: 17},
	{id: 52, name: 'Squadre', league: 18, championship: 18},
	{id: 53, name: 'Classifica', league: 18, championship: 18},
	{id: 54, name: 'Calendario', league: 18, championship: 18},
	{id: 55, name: 'Squadre', league: 19, championship: 19},
	{id: 56, name: 'Classifica', league: 19, championship: 19},
	{id: 57, name: 'Calendario', league: 19, championship: 19},
	{id: 58, name: 'Squadre', league: 20, championship: 20},
	{id: 59, name: 'Classifica', league: 20, championship: 20},
	{id: 60, name: 'Calendario', league: 20, championship: 20},
]