export class RoundModel {
	id: number;
	numberround: string;
}
export const ROUNDS: RoundModel[] =[
	{id: 1, numberround: '1 GIORNATA'},
	{id: 2, numberround: '2 GIORNATA'},
	{id: 3, numberround: '3 GIORNATA'},
	{id: 4, numberround: '4 GIORNATA'},
	{id: 5, numberround: '5 GIORNATA'},
	{id: 6, numberround: '6 GIORNATA'},
	{id: 7, numberround: '7 GIORNATA'},
	{id: 8, numberround: '8 GIORNATA'},
	{id: 9, numberround: '9 GIORNATA'},
	{id: 10, numberround: '10 GIORNATA'},
	{id: 11, numberround: '11 GIORNATA'},
	{id: 12, numberround: '12 GIORNATA'},
	{id: 13, numberround: '13 GIORNATA'},
	{id: 14, numberround: '14 GIORNATA'},
	{id: 15, numberround: '15 GIORNATA'},
	{id: 16, numberround: '16 GIORNATA'},
	{id: 17, numberround: '17 GIORNATA'},
	{id: 18, numberround: '18 GIORNATA'},
	{id: 19, numberround: '19 GIORNATA'},
	{id: 20, numberround: '20 GIORNATA'},
	{id: 21, numberround: '21 GIORNATA'},
	{id: 22, numberround: '22 GIORNATA'},
	{id: 23, numberround: '23 GIORNATA'},
	{id: 24, numberround: '24 GIORNATA'},
	{id: 25, numberround: '25 GIORNATA'},
	{id: 26, numberround: '26 GIORNATA'},
	{id: 27, numberround: '27 GIORNATA'},
	{id: 28, numberround: '28 GIORNATA'},
	{id: 29, numberround: '29 GIORNATA'},
	{id: 30, numberround: '30 GIORNATA'},
	{id: 31, numberround: '31 GIORNATA'},
	{id: 32, numberround: '32 GIORNATA'},
	{id: 33, numberround: '33 GIORNATA'},
	{id: 34, numberround: '34 GIORNATA'},
	{id: 35, numberround: '35 GIORNATA'},
	{id: 36, numberround: '36 GIORNATA'},
	{id: 37, numberround: '37 GIORNATA'},
	{id: 38, numberround: '38 GIORNATA'},
]

